# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[('Queued', 1), ('Running', 2), ('Canceled', 3), ('Failed', 4), ('Complete', 5)])),
                ('parameters_json', models.TextField()),
                ('progress', models.IntegerField(default=0)),
                ('cancel_signal', models.BooleanField(default=False)),
                ('result_json', models.TextField(default='null')),
            ],
        ),
    ]
